language: objective-c
before_install:
    - gem install cocoapods -v '0.39.0'
podfile: Tests/Podfile
script:
    - xctool -workspace DeltaDNA.xcworkspace -scheme "DeltaDNA iOS" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    - xctool test -workspace DeltaDNA.xcworkspace -scheme "DeltaDNA iOS" -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
    - xctool -workspace DeltaDNA.xcworkspace -scheme "DeltaDNA tvOS" -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO
    - xctool test -workspace DeltaDNA.xcworkspace -scheme "DeltaDNA tvOS" -sdk appletvsimulator ONLY_ACTIVE_ARCH=NO
