before_install:
    - gem install cocoapods
    - pod repo update > /dev/null
language: objective-c
podfile: Tests/Podfile
xcode_workspace: DeltaDNA.xcworkspace
matrix:
    fast_finish: true
    include:
        - {osx_image: xcode9.2,     env: 'SDK=iphonesimulator  SCHEME="DeltaDNA iOS"  DST="OS=11.2,name=iPhone 6"'}
        - {osx_image: xcode9.2,     env: 'SDK=iphonesimulator  SCHEME="DeltaDNA iOS"  DST="OS=8.4,name=iPhone 6"'}

        - {osx_image: xcode9.2,     env: 'SDK=appletvsimulator SCHEME="DeltaDNA tvOS" DST="OS=11.2,name=Apple TV"'}
        - {osx_image: xcode9.2,     env: 'SDK=appletvsimulator SCHEME="DeltaDNA tvOS" DST="OS=9.2,name=Apple TV 1080p"'}

        - {osx_image: xcode9.3beta, env: 'SDK=iphonesimulator  SCHEME="DeltaDNA iOS"  DST="OS=11.3,name=iPhone 6"'}
        - {osx_image: xcode9.3beta, env: 'SDK=iphonesimulator  SCHEME="DeltaDNA iOS"  DST="OS=8.4,name=iPhone 6"'}

        - {osx_image: xcode9.3beta, env: 'SDK=appletvsimulator SCHEME="DeltaDNA tvOS" DST="OS=11.3,name=Apple TV"'}
        - {osx_image: xcode9.3beta, env: 'SDK=appletvsimulator SCHEME="DeltaDNA tvOS" DST="OS=9.2,name=Apple TV 1080p"'}

    allow_failures:
        - {osx_image: xcode9.3beta, env: 'SDK=iphonesimulator  SCHEME="DeltaDNA iOS"  DST="OS=11.3,name=iPhone 6"'}
        - {osx_image: xcode9.3beta, env: 'SDK=iphonesimulator  SCHEME="DeltaDNA iOS"  DST="OS=8.4,name=iPhone 6"'}

        - {osx_image: xcode9.3beta, env: 'SDK=appletvsimulator SCHEME="DeltaDNA tvOS" DST="OS=11.3,name=Apple TV"'}
        - {osx_image: xcode9.3beta, env: 'SDK=appletvsimulator SCHEME="DeltaDNA tvOS" DST="OS=9.2,name=Apple TV 1080p"'}

script:
    - "xcodebuild -version"
    - "set -o pipefail"
    - "xcodebuild \
        -workspace $TRAVIS_XCODE_WORKSPACE \
        -scheme \"$SCHEME\" \
        -sdk $SDK \
        -quiet \
        -destination \"$DST\" \
        -enableCodeCoverage YES \
        clean build-for-testing | xcpretty"
    - "xcodebuild \
        -workspace $TRAVIS_XCODE_WORKSPACE \
        -scheme \"$SCHEME\" \
        -sdk $SDK \
        -quiet \
        -destination \"$DST\" \
        test-without-building | xcpretty"
